version: '3.0'

services:
    
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports: 
      - "3000:3000"
    networks:
      - app-network
    environment:
      - APP_PORT=3000
      - NODE_ENV=production
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=database
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart:  unless-stopped
    volumes:
      - ./backend/assets:/usr/share/nginx/html #assets
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:14.1-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - 5432:5432
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - app-network
    volumes:
      - frontend_dist:/app/dist/
    depends_on:
      - backend
    environment:
      - TZ=America/La_Paz
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - frontend_dist:/usr/share/html:ro
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./gateway/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network
    depends_on:
      - frontend
    restart: always

  redis:
    image: redis:7-alpine
    container_name: products-redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    
volumes:
  db_data:
  frontend_dist:

networks:
  app-network:
    driver: bridge