version: '3.8'

services:

  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - 5432:5432
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./app
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      NODE_ENV: production
    restart: always
    depends_on:
      - database

volumes:
  db_data:
networks:
  app-network:
    driver: bridge