apiVersion: v1
kind: Service
metadata:
  name: postsgres-headless
  namespace: tarea-clase7
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres


