apiVersion: v1
kind: Service
metadata:
  name: apirest-service
  namespace: tarea-clase6
  labels:
    app: apirest
spec:
  type: NodePort
  selector:
    app: apirest
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: http